add finish task  01-basics
js-tasks-ru/vue-20230710_pavel-ramanau pull request #2
Opened 2023-07-14 09:02 UTC by PaulRomanov

Верен ли  такой подход? 
Пришлось перенести button в template в компонент App.
Я не совсем понял как обойтись без компанента App.
Видимо вот так: 

import { createApp } from './vendor/vue.esm-browser.js';
const vm = createApp({
  data() {
    return {
      counter: 0
    };
  },
  methods: {
    count(){
      this.counter += 1;
    }
  },
}).mount('#app');

2023-07-14 09:03 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-14 12:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-07-16 16:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-07-16 20:53 UTC, ShGKme requested changes
Во всех задачах требуются исправления по комментариям

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <label><input type="radio" name="operator" value="divide" @click="divide"/> ➗</label>
Состояние этих радиокнопок не привязано к состоянию приложения. Изменение свойства `operator` не приводит к изменению выбранной радиокнопки.

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +    },
`result` - это вычисляемое свойство. В нём Vue хранит то значение, которое он сам вычисляет описанной вами функцией. В него нельзя присваивать значение (можно увидеть ошибку в консоли).

При этом во всех этих методах описаны вычисления, которые уже описаны в вычисляемом свойстве `result`. Нужны ли одни дважды?

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/App.vue
> +</template>
В области видимости шаблона все свойства экземпляра компонента. `this` в шаблоне не пишут.

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/App.vue
> +<style lang="scss" scoped></style>
Использование одно-файловых компонентов в целом — не ошибка. Но в этих темах их ещё не было, а в этой части задачника приложения подразумевается, как обычные документы с подключенным JS. 

Они должны работать и без сборщика. Если потребовалось добавить `.vue` файл, чтобы решение заработало - то была какая-то ошибка в коде.

Vue можно использовать без систем сборки. Так он работает и в следующих решённых задачах.

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +        <output class="col">{{result}}</output>
Обычно принято добавлять пробелы в текстовой интерполяции: `{{ result }}`

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Свойство `filteredEmails` не может быть одновременно и свойством данных компонента в `data`, и вычисляемым свойством в `computed`. Либо это свойство, значение которого вы устанавливаете самостоятельно (тогда это данные компонента в data), либо это свойство вычисляемое, вычисляется самим Vue по описанной функцией в `computed`.

2023-07-16 20:53 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="email in filteredEmails" :class="{ marked: isMatch(email) }">{{email}}</li>
Здесь выводятся отфильтрованные email-ы, где все выведенные email-ы промаркированы.
Требуется вывести все email-ы, и промаркировать только те, которые попадают под условие поиска.

2023-07-16 20:55 UTC, ShGKme commented
> Я не совсем понял как обойтись без компанента App. Видимо вот так:
> 
> import { createApp } from './vendor/vue.esm-browser.js'; const vm = createApp({ data() { return { counter: 0 }; }, methods: { count(){ this.counter += 1; } }, }).mount('#app');

Да, при корректном шаблоне этот код должен работать.

2023-07-17 07:35 UTC, PaulRomanov commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="email in filteredEmails" :class="{ marked: isMatch(email) }">{{email}}</li>
исправил

2023-07-17 07:36 UTC, PaulRomanov commented on 01-basics/03-MarkedList/script.js
> +  },
исправил

2023-07-17 07:37 UTC, PaulRomanov commented on 01-basics/02-VueCalculator/index.html
> +        <output class="col">{{result}}</output>
исправил

2023-07-17 07:39 UTC, PaulRomanov commented on 01-basics/01-CounterButtonApp/App.vue
> +<style lang="scss" scoped></style>
исправил

2023-07-17 07:39 UTC, PaulRomanov commented on 01-basics/01-CounterButtonApp/App.vue
> +</template>
исправил

2023-07-17 07:53 UTC, PaulRomanov commented on 01-basics/02-VueCalculator/script.js
> +    },
исправил

2023-07-17 07:53 UTC, PaulRomanov commented on 01-basics/02-VueCalculator/index.html
> +          <label><input type="radio" name="operator" value="divide" @click="divide"/> ➗</label>
исправил

2023-07-17 07:54 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-17 10:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-17 19:18 UTC, ShGKme requested changes
В `01-basics/03-MarkedList` требуется для практики работы с вычисляемыми свойствами сделать такое вычисляемое свойство, которое используется решением и помогает вывести почты сразу с маркировкой, без вызова метода проверки уже во время рендеринга.

Остальные задачи приняты

2023-07-17 19:18 UTC, ShGKme commented on 01-basics/04-MeetupTitle/index.html
> +          /> -->
Здесь нужно следить, что `fetchMeetupTitle` меняет `meetupId`, иначе состояние будет некорректным.

Кроме того, в решении без `watch` не будет работать обновление при смене `meetupId` другим путём.

2023-07-17 19:18 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +  },
Для использования функции в компоненте её не требуется переносить в методы. В методах компонента должны быть те функции, которые являются частью компонента. Изменяют или используют его свойства, обрабатывают события внутри компонента. Могут в методах также быть и простые функции, если они используются только в других методах этого же компонента и не нужны вне компонента.

Здесь же `fetchMeetupById` - самостоятельная функция.

Самостоятельную функцию могут использовать другие компоненты, функции и прочие модули приложения вне разрабатываемого компонента.

2023-07-17 19:18 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Это вычисляемое свойство никак не используется

2023-07-17 19:18 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="email in emails" :class="{ marked: isMatch(email) }">{{email}}</li>
Здесь при рендеринге вызывается метод проверки, подходит ли почта под условие маркировки. Это происходит при выводе каждой почты при каждом рендеринге. Хотя это довольно лёгкое вычисление, попробуйте подготовить данные таким образом, чтобы в шаблне их можно было сразу вывести с маркировкой.

2023-07-18 07:51 UTC, PaulRomanov commented on 01-basics/03-MarkedList/script.js
> +  },
удалил

2023-07-18 08:24 UTC, PaulRomanov commented on 01-basics/03-MarkedList/index.html
> +          <li v-for="email in emails" :class="{ marked: isMatch(email) }">{{email}}</li>
вроде поправил

2023-07-18 08:25 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-18 08:26 UTC, PaulRomanov commented on 01-basics/04-MeetupTitle/index.html
> +          /> -->
понял, удалил

2023-07-18 08:37 UTC, PaulRomanov commented on 01-basics/04-MeetupTitle/script.js
> +  },
а как это исправить?

2023-07-18 08:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-07-18 12:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-07-18 18:10 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-07-18 18:10 UTC, merged