add finished task 03-UiTransitionGroupFade
js-tasks-ru/vue-20230710_pavel-ramanau pull request #7
Opened 2023-07-24 13:49 UTC by PaulRomanov

2023-07-24 13:51 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-24 18:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-24 18:50 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-07-25 05:29 UTC, ShGKme requested changes
В `03-sfc/02-UiTransitionGroupFade` не работает анимация списка. Включение `scoped` в стилях ломает работу стилей. Требуется найти способ оставить `scoped`, но починить стили компонента.

В `04-vue-cli/01-UiFormGroup1` требуется использовать привязку классов через объект для классов-модификаторов.

2023-07-25 05:29 UTC, ShGKme commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div class="form-group" :class="inline ? 'form-group_inline' : ''">
Во Vue, когда требуется добавить класс по условию, принято использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому выражению требуется добавлять.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects 

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы. 

И не требуется делать `else` с пустой строкой в тернарном операторе.

2023-07-25 05:29 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +  },
Это вычисляемое свойство ничего не вычисляет, просто возвращая фиксированную строку. Такой класс можно напрямую использовать в шаблоне без вычисления и динамической привязки, так как он не меняется и не вычисляется.

2023-07-25 05:29 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +  },
Вычисление его в вычисляемом свойстве также не делает его более уникальным. Это также обычный класс, который может использоваться в любой части приложения.

2023-07-25 08:33 UTC, PaulRomanov commented on 04-vue-cli/01-UiFormGroup1/components/UiFormGroup.vue
> +  <div class="form-group" :class="inline ? 'form-group_inline' : ''">
исправил

2023-07-25 11:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-25 11:13 UTC, PaulRomanov commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +  },
я не знаю как решить эту задачу

2023-07-25 14:48 UTC, PaulRomanov commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +  },
сделал

2023-07-25 14:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-26 08:36 UTC, ShGKme commented on src/assets/icons/icon-trash.svg
Цвет SVG иконки можно менять через CSS, если подключать inline

2023-07-26 08:36 UTC, ShGKme commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +.fade-list > :deep() {
Этот селектор не работает, функция в псевдо-классе не может быть пустой, а `deep` применяется к "никакому" селектору.

В итоге анимация анимации пропала.

2023-07-26 08:36 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
Здесь в качестве времени таймера используется аргумент `time`. Но по условию эти методы имеют только один аргумент `message`. Методы должны работать корректно по умолчанию с таймером в 5000, когда никакое другое значение не передано.

2023-07-26 08:36 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      }, time);
Удаление с `messagesAll.shift()` работает, только если сообщения всегда удаляются в том же порядке, в котором добавляются. Это верно только для случая, когда `time` фиксированный. Но в вашем решении можно передавать любой `time`, и новое сообщение может иметь `time` больше предыдущего.

2023-07-26 08:36 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
Этот метод мутирует входной параметр

2023-07-26 08:36 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      icon: 'check-circle',
Эти классы передаются в компоненте `TheToaster`, но описаны и используются внутри компонента `UiToast`. Это не очень удобно для пользователя компонента, который должен доставать класс из исходников используемого компонента. И не очень удобно для поддержки компонента, так как использование компонента сломается при рефакторинге и изменении имени класса (получается неявный интерфейс).

Можно либо передавать на компонент классы, которые описаны здесь же, через `class=""`.

Либо вместо передачи класса и иконки передавать тип тоста, а уже самому тосту давать решать, как именно рендерить тост такого типа.

2023-07-26 08:36 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  name: 'UiToast',
По названию `UiToast` этот компонент выводит один тост, но фактически выводит множество тостов.

2023-07-26 08:36 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
К имени параметра обычно не добавляют такие суффиксы как `all`, если не требуется явно указать, что это не просто "массив сообщений", а именно массив неких "всех" сообщений (и компонент не предназначен для рендеринга "не всех" сообщений".

2023-07-26 08:59 UTC, PaulRomanov commented on 03-sfc/02-UiTransitionGroupFade/components/UiTransitionGroupFade.vue
> +.fade-list > :deep() {
поправил

2023-07-26 09:04 UTC, PaulRomanov commented on src/assets/icons/icon-trash.svg
да, через CSS свойство fill, но ведь у нас svg подключено через тэг img

2023-07-26 09:16 UTC, PaulRomanov commented on src/assets/icons/icon-trash.svg
.iconTrash {  filter: hue-rotate(360deg); }
Пододйт такое решение: дополнительный класс?

2023-07-26 09:20 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      }, time);
исправил

2023-07-26 09:22 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  name: 'UiToast',
изменил на UiToasts

2023-07-26 09:25 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
переименовал

2023-07-26 09:37 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  },
исправил через копию массива

2023-07-26 14:37 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-26 14:40 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      icon: 'check-circle',
переделал

2023-07-26 14:58 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
переделал

2023-07-28 11:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-29 10:39 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-29 10:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-29 16:24 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-07-30 03:25 UTC, ShGKme requested changes
В `04-vue-cli/03-UiDropdown1` требуется исправление по комментариям.

2023-07-30 03:25 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    <div class="dropdown__menu" role="listbox" :style="{ display: isDropdownOpen ? 'flex' : 'none' }">
Для сокрытия элементов с `display: none` можно использовать специальную директиву `v-show`

2023-07-30 03:25 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`selectedOption` - не собственные данные компонента. Компонент никогда сам не определяет, что именно "выбранный вариант". Это всегда вычисление на основе входных параметров - списка варианта и значения текущего выбранного варианта. Лучше это явно описывать, как вычисляемое свойство. Так будет и более простое явное решение (явно описывается, как вычисляется выбранный вариант), и сложнее будет совершить ошибку.

Например, сейчас компонент не поддерживает обновление списка вариантов `options`.

2023-07-30 03:25 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
В компоненте не может одновременно работать и удаление "первого в очереди" тоста по таймеру и удаление тоста по кнопке удаления. После того, как тост был удалён кнопкой, таймер его удаления остаётся. В итоге он просто удалит следующий тост.

1. Добавляем тост 1.
2. Через 4 секунды добавляем ещё один тост 2.
3. Удаляем первый тост кликом.
4. Прошло 5 секунд - по таймеру удаляется первый тост в очереди - тост 2 (хотя он весит всего 1 секунду).

2023-07-30 03:25 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +import { ToastType, ToastIconMap  } from '../../../src/constants/constants.js';
Путь слишком далеко уходить назад, чтобы потом вернуться почти в ту же директорию

2023-07-31 09:31 UTC, PaulRomanov commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
исправил, перенес в блок computed

2023-07-31 09:36 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +import { ToastType, ToastIconMap  } from '../../../src/constants/constants.js';
исправил с помощью Алиаса путей

2023-07-31 09:46 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +  },
Добавил   проверку, есть ли тост с такими же type и message в массиве messages перед добавлением нового тоста. Если такой тост уже есть, то новый не добавляется, а существующему обновляется таймер удаления.

2023-07-31 09:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-07-31 09:54 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-01 18:43 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`selectedOption` - вычисляемое свойство. Его значение устанавливает сам Vue по результату вычисления. В него не нужно и нельзя присваивать новое значение (будет ошибка в консоли).

2023-08-01 18:43 UTC, ShGKme commented on src/constants/constants.js
Вещи, связанные с одной конкретной задачей, лучше хранить в директории этой же задачи.

2023-08-01 18:43 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/__tests__/MeetupsCalendar.test.js
Удаление тестов задачи не считается за её решение :)

2023-08-01 18:43 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      const existingToast = this.messages.find((toast) => toast.type === type && toast.message === message);
Этот код делает что-то новое, не описанное в условии задачи.

Если пользователь компонента добавляет три тоста - то должны выводиться три тоста. Даже если все три тоста будут иметь одинаковый текст. Тосты вообще часто имеют простой одинаковый текст, например, `Сохранено` или `Успешно`.

Если человек быстро выполняет три действия, которые сохраняют что-то, он хочет три раза видеть "Успешно сохранено", а не 15 секунд видеть сообщение о первом сохранении.

Эта проверка не помогает с предыдущей проблемой, когда удалялся лишний тост. От удаления лишнего тоста помогает проверка `if (index !== -1)` в таймере

2023-08-02 06:46 UTC, PaulRomanov commented on src/constants/constants.js
удалил целиком, она случайно попала. Чтобы PR закрыть.  А Календарь чтобы попал в следующий.

2023-08-02 06:46 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/__tests__/MeetupsCalendar.test.js
удалил целиком, она случайно попала. Чтобы PR закрыть. А Календарь чтобы попал в следующий.

2023-08-02 06:54 UTC, PaulRomanov commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
исправил

2023-08-02 08:29 UTC, PaulRomanov commented on src/constants/constants.js
я так и не смог полностью избавиться от файла constants.js

2023-08-02 08:45 UTC, PaulRomanov commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +      const existingToast = this.messages.find((toast) => toast.type === type && toast.message === message);
вроде поправил

2023-08-02 08:50 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-03 19:27 UTC, ShGKme commented on src/constants/constants.js
От него не обязательно избавляться, но именно в рамках задачника - лучше хранить в директории задачи (`04-vue-cli/03-UiDropdown1/`), а не `src` всего задачника

2023-08-03 19:42 UTC, ShGKme reviewed
Все решённые задачи приняты, но требуется добавить решение удалённой задачи

2023-08-04 07:53 UTC, PaulRomanov commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +    <div class="dropdown__menu" role="listbox" :style="{ display: isDropdownOpen ? 'flex' : 'none' }">
заменил

2023-08-04 07:58 UTC, PaulRomanov commented on src/constants/constants.js
перенес в задачу 02-TheToaster

2023-08-04 08:01 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-04 08:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-04 12:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-04 16:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-04 17:22 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-04 19:21 UTC, ShGKme commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +    }
Это условие лишнее, оно не влияет на результат

2023-08-04 19:21 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +          <button type="submit" class="button button_primary button_block" @click.prevent="handleSubmit">Войти</button>
Обрабатывать клик по кнопке для обработки сабмита формы - некорректно. Кнопка - лишь один из способов сабмита формы. Но сабмит - событие именно самой формы. Оно также срабатывает, например, при нажатии на `Enter`. В этой задаче и обработка сабмита уже установлена на элемент формы.

2023-08-05 07:02 UTC, PaulRomanov commented on 05-vue-router/03-ScrollBehavior/router/index.js
> +    }
исправил

2023-08-05 07:05 UTC, PaulRomanov commented on 05-vue-router/01-AuthPages/views/PageLogin.vue
> +          <button type="submit" class="button button_primary button_block" @click.prevent="handleSubmit">Войти</button>
исправил

2023-08-05 07:09 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-06 11:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-07 13:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-07 20:05 UTC, ShGKme commented on 05-vue-router/01-AuthPages/views/PageRegister.vue
> +          <button type="submit" class="button button_primary" @click.prevent="handleSubmit">Зарегистрироваться</button>
Аналогично предыдущему компоненту, обрабатываться должен именно сабмит формы, не клик по кнопке.

2023-08-07 20:05 UTC, ShGKme commented on 05-vue-router/04-UiTabsLink/components/UiTabsLink.vue
> +  },
Это решение работает, но значительно сложнее и дублирует функциональность, которую VueRouter умеет делать из коробки.

У `RouterLink` есть параметр, через который можно указать, какой класс должен быть у ссылки, когда она "активная" (ведёт на текущую страницу).

В условии задачи есть ссылка на документацию компонента. Она не самая простая, но там можно найти нужный параметр.

2023-08-07 20:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Здесь для изменения месяца меняется только номер месяца, а число остаётся тем же. Такое решение не всегда работает, так как не в любом месяце те же дни, что и в соседнем.

Например, если сегодня 31 января, то следующим месяцем не может быть 31 февраля. Chrome превратит 31 февраля в 3 марта, а Firefox выкинет ошибку.

2023-08-07 20:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +  },
Локализация должна быть не `'RU'`, а соответствовать настройкам пользователя и браться из `navigator.language`.

2023-08-07 20:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +  },
Кроме того, `titelData` - не данные компонента. Это не самостоятельное свойство, у него нет обственного значения. Компонент уже хранит текущую дату в `date`, а форматированная дата - результат вычисления от `date`. `titelData` должен быть либо вычисляемым свойством, либо методом.

2023-08-07 20:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Именно эта часть приводит к некорректной работе календаря

2023-08-07 20:05 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Хотя для формирования календаря это не важно, лучше везде работать в функциях в UTC.

Методы `getMonth`, `get*`, `setMonth` и т.д. - работают в локальном часовом поясе и у разных пользователей дадут разный результат. Для формирования ячеек календаря это _может_ быть не важно. Но это усложнит другие места и может приводить к проблемам:
- Даты митапов в данных именно в UTC
- `new Date(currentYear, currentMonth, 1)` - для отрицательных часовых поясов (западнее западной европы) даст предыдущий день - последний день предыдущего месяца

Нужно использовать методы нулевого часового пояса: `getUTCDate` и т.д.

2023-08-08 11:56 UTC, PaulRomanov commented on 05-vue-router/01-AuthPages/views/PageRegister.vue
> +          <button type="submit" class="button button_primary" @click.prevent="handleSubmit">Зарегистрироваться</button>
исправил

2023-08-08 14:49 UTC, PaulRomanov commented on 05-vue-router/04-UiTabsLink/components/UiTabsLink.vue
> +  },
да, действительно, как-то пропустил. селал через activeClass

2023-08-08 14:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-08 15:04 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
вроде поправил

2023-08-08 15:17 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +  },
испрвил

2023-08-08 15:23 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
исправвил

2023-08-08 15:31 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-08 17:53 UTC, ShGKme reviewed
В календаре всё ещё отсутствуют дни предыдущего/следующего месяцев при необходимости, а а также данные в ячейках. Остальные задачи приняты.

![image](https://github.com/js-tasks-ru/vue-20230710_pavel-ramanau/assets/25978914/3a465d78-9f16-4640-850c-165848e94889)

2023-08-08 17:53 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      }
Такое решение проблемы с месяцами - не совсем работает. `newDate.setUTCMonth(newDate.getUTCMonth() - 1);` всё равно упадёт с ошибкой в Firefox.

Более простое решение - не использовать вообще сегодняшнее число, как текущее. А использовать любой день, который есть в любом месяце и не крайний. Например, явно зафиксировать 15 число.

2023-08-08 19:05 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      }
исправил

2023-08-08 19:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-09 17:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-10 08:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-10 21:37 UTC, ShGKme commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </component>
`v-bind="$attrs"` с `inheritAttrs: false` здесь лишние. Все параметры уже сами наследуются, так как `<component>` - корневой элемент. В итоге это реализует функциональность, которая работает из коробки. Вручную передавать атрибуты нужно, когда оборачиваемый узел - не корневой.

2023-08-10 21:37 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +  </component>
Аналогично

2023-08-10 21:37 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    },
На мой взгляд, статические классы, которые всегда есть у элемента, можно описывать явно в шаблоне через обычный атрибут `class="button`. Так будет видно и основные классы верстки, и какие классы определяются динамически.

При этом для классов, которые добавляются по условию (как `button_block` удобно использовать синтаксис с объектом. И не потребуется делать `else` с пустой строкой в тернарном операторе или массив с пустым именем класса.

2023-08-11 03:56 UTC, PaulRomanov commented on 06-wrappers/01-UiLink/components/UiLink.vue
> +  </component>
исправил

2023-08-11 03:56 UTC, PaulRomanov commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +  </component>
исправил

2023-08-11 04:10 UTC, PaulRomanov commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    },
исправил

2023-08-11 04:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-11 05:11 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-11 16:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-11 20:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    },
Это не то, как описываются условия добавления классов во Vue. В объекте описывается объект, где ключ - имя класса, а значение - булевый флаг добавления класса, то есть условие добавление класса.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects 

В целом лучше не использовать `true` и `false` как ключи в объекте. Здесь это не значения `true` и `false` из JS, а обычные строки `"true", "false"`. Такой объект работает, когда при приведении `boolean` к строке получается правильная строка, но сломается, если будет `truthy/falsy` значения.

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
Аналогично предыдущей задаче, если здесь использовать синтаксис привязки классов объектом, все классы опишутся одним общим простым объектом без пустых значений.

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    ]"
Класс `'input-group_icon'` должен быть только, когда у поля ввода есть иконка (передана через один из слотов).

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    ]"
`input-group_icon-left` и `input-group_icon-right` можно описать одним объектом

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    </component>
Здесь может рендериться либо `input`, либо `textarea`. Оба - HTML элементы, у которых не может быть события `@update:modelValue`. Такие события могут быть только у компонентов. Поэтому подписка на событие `@update:modelValue="localValue = $event"` ни на что не влияет

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      deep: true,
Глубокое отслеживание здесь не требуется. `localValue` - строк, у строки нет вложенных значений, как в объектах или массивах

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +        }
Проверка `newValue !== this.localValue` здесь тоже не нужна. Так как это строки, то при равном значении присваивание ничего не изменит. Подобная проверка нам была нужна в компоненте форме, так как так хранился объект, где по ссылке был тот же по значению объект. (`{ a: 1 } !== { a: 1 }`)

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
Это не является ошибкой, но локальное состояние  `localValue` этому компоненту не требуется. Такое состояние нужно только в двух случаях:
- Если компонент должен уметь работать на только локальном состоянии без пропса
- Если требуется копия объекта, чтобы не мутировать переданный объект.

Компонент ввода всегда используется только для того, чтобы редактировать полученную от родителя строки. Компонент ввода не нужен, если введённым значением не пользуется пользователь компонента. Без локального состояние реализация компонента проще.

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    </component>
Директива `v-model` не работает "полноценно" на динамическом компоненте.

http://learn.javascript.ru/taskbook/vue-20230710/workspace/wrappers#4-1-dinamicheskiy-komponent-i-v-model

Vue не знает, какой именно узел здесь будет рендеритсья (может быть любой) и раскрывает `v-model` - как директиву на компоненте: для параметра `modelValue` и события `update:modelValue`. Но и `input`, и `textarea` должны получать значение в параметр `value` и отдают введённое значение по событию `@input`.

2023-08-12 19:00 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    </component>
При этом, если бы здесь был не динамический компонент `<component :is`, а напрямую `input`, то решение тоже бы работало не совсем корректно.

При вводе значения происходило бы два действия:
1. Присваивалось новое значение в `localValue` за счёт двустороннего связывания, где в `watch` за ним вы порождаете событие `this.$emit("update:modelValue", newValue)`
2. Сработало бы событие `@input`, по которому вы также порождаете событие `$emit('update:modelValue', $event.target.value)`

В итоге при вводе значения событие порождалось бы дважды на каждый ввод.

2023-08-12 19:00 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      }
Из-за того, что `getUTCDay` возвращает неделю, где ПН - 1, а воскресение не 7, а 0, получается сдвиг на один день.

![image](https://github.com/js-tasks-ru/vue-20230710_pavel-ramanau/assets/25978914/ff451504-37c0-4df4-b84b-1dc279e68d15)

Если сегодня "Понедельник" (`getUTCDay = 1`), то дней предыдущего месяца - 0, и цикл не должен сделать ни одного шага.

Соответственно:

День | getUTCDay | Дней предыдущего месяца | У вас дней
---|---|---|---
ПН | 1 | 0 | 1
ВТ | 2 | 1 | 2
СР | 3 | 2 | 3
ЧТ | 4 | 3 | 4
ПТ | 5 | 4 | 5
СБ | 6 | 5 | 6
ВС | 0 | 6 | 0

2023-08-12 19:00 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      }
Чтобы исправить проблему, `startDayOfWeek` должен быть на 1 меньше, но при этом Воскресение должно быть 6 (а не -1).

Математическое решение:
```js
startDayOfWeek = (firstDay.getUTCDay() - 1 + 7) % 7
```

- `-1` - уменьшает на 1
- `(... + 7) % 7` - делает значение в диапазоне 0..6

2023-08-12 19:00 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
Здесь осталась проблема из старого комментария.

Месяц получается некорректным.
С 31 января действие `newDate.setUTCMonth(newDate.getUTCMonth() + 1);` переходит сразу в март, потому что 31 февраля не существует.

Проверка в условии не помогает, она никак не влияет на неверно изменённый месяц. Просто заменяет 3 марта на 15 марта, когда должен быть февраль.

Дополнительные условия здесь не нужны, достаточно всегда работать в такой день, когда безопасно менять номер месяца, например, ещё до смены месяца сразу установить 15 день.

2023-08-12 19:00 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      const dayNumber = targetDate.getUTCDate ? targetDate.getUTCDate() : null;
Последняя проблема. `targetDate` у вас - дата числом. У числа не может метода `getUTCDate`. Нужно лишь привести к дате.

```js
const dayNumber = new Date(targetDate).getUTCDate()
```

2023-08-12 19:00 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      const dayNumber = targetDate.getUTCDate ? targetDate.getUTCDate() : null;
Или ещё проще, вообще не строить дату и просто сравнивать даты числом в фильтре.

```js
const filteredMeetups = this.meetups.filter((meetup) => meetup.date === targetDate);
```

2023-08-12 20:33 UTC, PaulRomanov commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    },
isBlock() {
      return this.block ? 'button_block' : '';
    },
так пойдет?

2023-08-12 20:35 UTC, PaulRomanov commented on 06-wrappers/02-UiButton/components/UiButton.vue
> +    },
или все же лучше так: 
:class="[classes, {'button_block':block}]"

2023-08-12 20:52 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
:class="{'form-control_sm': small, 'form-control_rounded': rounded, 'textarea': multiline}"
 так локаничнее и не нужны вычисляемые свойства =)

2023-08-12 20:54 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      deep: true,
убрал

2023-08-12 21:04 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    ]"
:class="[
      {'input-group_icon': $slots['left-icon'] || $slots['right-icon']},
      {
        'input-group_icon-left': $slots['left-icon'],
        'input-group_icon-right': $slots['right-icon'],
      },
    ]"
    исправил

2023-08-12 21:11 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +        }
исправил

2023-08-12 21:52 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    },
просто была проблема с мутированием.

2023-08-12 21:52 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    </component>
внес изменения

2023-08-12 21:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-13 12:20 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      }
исправил

2023-08-13 13:01 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +    },
исправил.

2023-08-13 13:02 UTC, PaulRomanov commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +      const dayNumber = targetDate.getUTCDate ? targetDate.getUTCDate() : null;
исправил

2023-08-13 13:05 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-13 21:11 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    ]"
Вместо массива двух объектом можно сделать просто 1 объект

2023-08-13 21:11 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      }"
Класс `textarea` лишний, для него нет стилей

2023-08-13 21:11 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  emits: ["update:modelValue"],
Для использования директивы `v-model` параметр и событие должны называться особым образом.

Аргумент директивы `v-model` - имя параметра с двусторонним связыванием.
Событие для обновления директивой - `update:имя-параметра`.

Например, `v-model:foo="variable"` - превращается в:
- `:foo="variable"` - привязку параметра `foo`
- `@update:foo="variable = $event"` - обновление привязанной переменной по событию

По умолчанию аргумент - `model-value`. То есть `v-model:model-value="variable"` тоже самое, что `v-model="variable"`.

2023-08-13 21:11 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  emits: ["update:modelValue"],
Нужно, чтобы компонент можно было использовать с директивой `v-model`. Тогда параметр должен называться именно `modelValue`, а не `value`.

2023-08-13 21:11 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  emits: ["update:modelValue"],
При этом у вас уже есть событие обновления параметра `update:modelValue`. Но нет параметра `modelValue`.

2023-08-13 21:11 UTC, ShGKme commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  },
Напомню, что решение будет сильно проще без локального состояния `localValue`. Компонент выводит в инпуте то значение, которое ему передают в пропс. А при вводе сразу отдаёт его обратно.

2023-08-14 06:44 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +    ]"
исправил

2023-08-14 06:47 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +      }"
удалил

2023-08-14 07:19 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  emits: ["update:modelValue"],
спасибо, вот в чем была ошибка, которая сломало  мне мозг =)

2023-08-14 07:33 UTC, PaulRomanov commented on 06-wrappers/03-UiInput/components/UiInput.vue
> +  },
исправил

2023-08-14 07:41 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-14 13:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-08-14 13:32 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-08-14 19:08 UTC, ShGKme approved these changes
Все задачи приняты 🎉

2023-08-14 19:08 UTC, ShGKme commented on 04-vue-cli/04-MeetupsCalendar/components/MeetupsCalendar.vue
> +          >
Сейчас во время рендеринга вызывается метод. Вызывать метод в шаблоне в целом обычно не лучшая практика. Это делает шаблон не декларативным, и требует дополнительно проверять, что метод не имеет побочных эффектов и производительный. Иногда это допустимо, когда метод используется для форматирования вывода или немного упрощает код в компоненте.

Но метод `filterMeetupsByDate` здесь используется для описания логики работы с данными - формирует массив данных для вывода прямо во время рендеринга. Это уже перетекание логики обработки данных в шаблон, при этом неоптимальное.

В итоге сейчас при рендеринге КАЖДОЙ ячейки календаря происходит перебор всех-всех митапов (включая те, которые вообще не относятся к этому месяцу или уже выводились в другой ячейки) для проверки, а не попадает ли этот митап в эту ячейку. Потом ещё раз для следующей ячейки. И так для всех дней месяца. И всё это повторяется при каждом ререндеринге компонента, даже если результат не изменится.

Вместо этого лучше готовить данные для их удобного вывода без дополнительных перевычислений.

2023-08-14 19:11 UTC, merged